homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 309
  unit_system: imperial
  time_zone: America/Chicago

frontend:
cloud:
config:
updater:
discovery:
  ignore:
    - samsung_tv
conversation:
history:
logbook:
sun:
system_health:
map:
automation: !include automations.yaml
binary_sensor: !include binary_sensor.yaml
sensor: !include sensors.yaml
media_player: !include media_players.yaml
device_tracker: !include device_tracker.yaml
zone: !include zones.yaml
group: !include groups.yaml
camera: !include cameras.yaml
notify: !include notifications.yaml
alarm_control_panel: !include alarm_control_panel.yaml

ffmpeg:
  ffmpeg_bin: /usr/bin/ffmpeg

logger:
  default: error
  logs:
    homeassistant.components.device_tracker: critical
    homeassistant.components.camera: critical

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret http_password
  # Uncomment this if you are using SSL or running in Docker etc
  base_url: !secret http_base_url
  use_x_forwarded_for: true
  # You must set the trusted proxy IP address so that Home Assistant will properly accept connections
  # Set this to your NGINX machine IP, or localhost if hosted on the same machine.
  trusted_proxies: 10.0.0.5 


nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret
  sensors:
    monitored_conditions:

ring:
  username: !secret ring_username
  password: !secret ring_password

climate:
  platform: nest

# Text to speech
tts:
  - platform: google
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300

#wink:

emulated_hue:
  type: alexa
  listen_port: 80

ifttt:
  key: !secret ifttt_key

arlo:
  username: !secret arlo_username
  password: !secret arlo_password

august:
  login_method: email
  username: !secret august_username
  password: !secret august_password

neato:
  username: !secret neato_username
  password: !secret neato_password

weather:
  - platform: darksky
    api_key: !secret darksky_api_key
