- platform: samsungtv
  host: 192.168.1.124
  name: Samsung Smart TV
  mac: 0c:89:10:6f:0d:09
- platform: kodi
  host: 192.168.1.217
  name: OSMC Living Room
- platform: firetv
- platform: cast
- platform: roku
