- platform: yr
- platform: moon
- platform: wunderground
  api_key: !secret wunderground_key
  monitored_conditions:
    - temp_high_record_f
    - temp_high_1d_f
    - temp_f
    - heat_index_f
    - feelslike_f
    - temp_low_1d_f
    - temp_low_record_f
    - precip_1d
    - precip_1d_in
    - wind_mph
    - wind_1d_mph
    - alerts
    - weather_1d
    - weather_1n
    - weather_2d
    - weather_2n
    - weather_3d
    - weather_3n
    - weather_4d
    - weather_4n
- platform: systemmonitor
  resources:
  - type: disk_use_percent
    arg: /
  - type: memory_free
  - type: processor_use
  - type: network_in
    arg: wlan0
  - type: network_out
    arg: wlan0
  - type: last_boot
- platform: pushbullet
  api_key: !secret pushbullet_key
  monitored_conditions:
    - application_name
    - body
    - sender_email

