- platform: yr
- platform: moon
- platform: systemmonitor
  resources:
  - type: disk_use_percent
    arg: /
  - type: memory_free
  - type: processor_use
  - type: network_in
    arg: wlan0
  - type: network_out
    arg: wlan0
  - type: last_boot
- platform: pushbullet
  api_key: !secret pushbullet_key
  monitored_conditions:
    - application_name
    - body
    - sender_email
- platform: ring
- platform: arlo
  monitored_conditions:
    - captured_today
    - last_capture
    - total_cameras
    - battery_level
    - signal_strength
    - temperature
    - humidity
    - air_quality
